# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: stock-service

frameworkVersion: '2'

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 5000
  dynamodb:
    stages:
      - dev
    start:
      inMemory: true
      migrate: true
      port: 8000
  dynamodbStream:
    host: localhost
    port: 8000
    pollForever: false
    region: ${self:provider.region}
    streams:
      - table: stockInboundEvents
        functions:
          - stockInboundProcessing
      - table: stockOutboundEvents
        functions:
          - stockOutboundProcessing
  serverless-offline-sns:
    accountId: 123456789012
    host: 0.0.0.0
    sns-endpoint: http://localhost:6000

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment: ${file(.env.yml):${opt:stage, self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:us-east-1:063061419719:table/stockTable
        - arn:aws:dynamodb:us-east-1:063061419719:table/stockOutboundEvents
        - arn:aws:dynamodb:us-east-1:063061419719:table/stockInboundEvents

package:
  exclude:
    - aws-sdk

functions:
  stockCreate:
    handler: src/functions/create/create.stockCreateHandler
    events:
      - httpApi:
          path: /stock
          method: post
  stockInbound:
    handler: src/functions/inbound/inbound.stockInboundHandler
    events:
      - httpApi:
          path: /stock/{stockId}/inbound
          method: put
  stockOutbound:
    handler: src/functions/outbound/outbound.stockOutboundHandler
    events:
      - httpApi:
          path: /stock/{stockId}/outbound
          method: put

  stockInboundProcessing:
    handler: src/functions/inbound-processing/inbound-processing.stockInboundProcessingHandler
    events:
      # - stream: arn:aws:dynamodb:us-east-1:063061419719:table/stockInboundEvents/stream/2021-01-21T03:42:24.276

  stockOutboundProcessing:
    handler: src/functions/outbound-processing/outbound-processing.stockOutboundProcessingHandler
    events:
      # - stream: arn:aws:dynamodb:us-east-1:063061419719:table/stockOutboundEvents/stream/2021-01-21T03:42:24.477
  testeSns1:
    handler: src/functions/teste.teste
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sns'
                - ${opt:region, self:provider.region}
                - ${file(.env.yml):${opt:stage, self:provider.stage}.AWS_ACCOUNT_ID}
                - product-created
          topicName: product-created

resources:
  - ${file(./resources/tables/stock.yml)}
  - ${file(./resources/tables/stock-inbound-events.yml)}
  - ${file(./resources/tables/stock-outbound-events.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-plugin-offline-dynamodb-stream
  - serverless-offline-sns
  - serverless-offline
